name: imgeval
channels:
- conda-forge
- pytorch
dependencies:
- brotli-python=1.1.0
- bzip2=1.0.8
- ca-certificates=2024.8.30
- certifi=2024.8.30
- cffi=1.17.1
- charset-normalizer=3.4.0
- cpython=3.12.7
- filelock=3.16.1
- freetype=2.12.1
- gmp=6.3.0
- gmpy2=2.1.5
- h2=4.1.0
- hpack=4.0.0
- hyperframe=6.0.1
- idna=3.10
- jinja2=3.1.4
- lcms2=2.16
- lerc=4.0.0
- libblas=3.9.0
- libcblas=3.9.0
- libcxx=19.1.2
- libdeflate=1.22
- libexpat=2.6.3
- libffi=3.4.2
- libgfortran5=13.2.0
- libjpeg-turbo=3.0.0
- liblapack=3.9.0
- libopenblas=0.3.24
- libpng=1.6.44
- libsqlite=3.46.1
- libtiff=4.7.0
- libwebp-base=1.4.0
- libxcb=1.17.0
- libzlib=1.3.1
- llvm-openmp=15.0.7
- markupsafe=3.0.1
- mpc=1.3.1
- mpfr=4.2.1
- mpmath=1.3.0
- ncurses=6.5
- networkx=3.4.1
- numpy=2.1.2
- openjpeg=2.5.2
- openssl=3.3.2
- pillow=10.4.0
- pip=24.2
- pthread-stubs=0.4
- pycparser=2.22
- pysocks=1.7.1
- python=3.12.7
- python_abi=3.12
- pytorch=2.4.1
- pyyaml=6.0.2
- readline=8.2
- requests=2.32.3
- setuptools=75.1.0
- sympy=1.13.3
- tk=8.6.13
- torchvision=0.19.1
- typing_extensions=4.12.2
- tzdata=2024b
- urllib3=2.2.3
- wheel=0.44.0
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.5
- xz=5.2.6
- yaml=0.2.5
- zstandard=0.23.0
- zstd=1.5.6
- pip:
  - Brotli==1.1.0
  - certifi==2024.8.30
  - cffi==1.17.1
  - charset-normalizer==3.4.0
  - contourpy==1.3.0
  - cycler==0.12.1
  - filelock==3.16.1
  - fonttools==4.54.1
  - gmpy2==2.1.5
  - h2==4.1.0
  - hpack==4.0.0
  - hyperframe==6.0.1
  - idna==3.10
  - imageio==2.36.0
  - Jinja2==3.1.4
  - kiwisolver==1.4.7
  - lazy_loader==0.4
  - MarkupSafe==3.0.1
  - matplotlib==3.9.2
  - mpmath==1.3.0
  - networkx==3.4.1
  - numpy==2.1.2
  - OpenEXR==3.3.1
  - packaging==24.1
  - pillow==10.4.0
  - pip==24.2
  - pycparser==2.22
  - pyexr==0.4.0
  - pyparsing==3.2.0
  - PySocks==1.7.1
  - python-dateutil==2.9.0.post0
  - PyYAML==6.0.2
  - requests==2.32.3
  - scikit-image==0.24.0
  - scipy==1.14.1
  - setuptools==75.1.0
  - six==1.16.0
  - sympy==1.13.3
  - tifffile==2024.9.20
  - torch==2.4.1
  - torchvision==0.19.1
  - typing_extensions==4.12.2
  - urllib3==2.2.3
  - wheel==0.44.0
  - zstandard==0.23.0
